[build]
builder = "DOCKERFILE"
dockerfilePath = "infrastructure/docker/api.Dockerfile"
dockerfileTarget = "production"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
